name: UnitTest

on:
  push:
    branches: [ main ]
    paths:
      - 'fbs/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'fbs/**'
      - 'tests/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      name:
        description: 'Workflow run name'
        required: true
        default: 'Manual unittest'
      reason:
        description: 'Reason'
        required: true
        default: 'Test modules'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install jaxlib jax
          pip install -r requirements.txt
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e .
      - name: Do the unit tests
        run: |
          pip install pytest
          pytest tests/
      - name: Logging
        run: |
          echo "This is ${{ github.event.inputs.name }}!"
          echo "Reason is ${{ github.event.inputs.reason }}!"
